-- Arbitrage-only schema (RapidAPI-only)
--
-- As of the RapidAPI migration, this app does not require Supabase.
-- Arbitrage opportunities are fetched live server-side and are not persisted.
--
-- This file is intentionally minimal and can be left unapplied.
